name: Utils
version: 1.0
main: de.xenon.playerutils.Plugin
author: Rxbsi, Verronix

commands:
  utils:
  workbench:
  chatevents:
  daytime:
  whitelistgui:
  health:
  gm:
  bannkick:
  invsee:
  vanish:
  fly:
  teleportutil:
  troll: